---
- name: Debug Example
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Ping
      file:
        path: /home/admin1/Erzhan_hi_test2022
        state: touch
        owner: admin1
        group: admin1
        mode: '777'
