---
- name: Debug Example
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Ping
      file:
        path: /admin1/home/erzhan
        state: touch
        owner: admin1
        group: admin1
        mode: '0644'
